### ISSUE TITLE
lions problems

### ISSUE THREAD

**Issue by b12loroc** [ababaian/LIONS#1]
I have a problem with LIONS.
scripts/ChimericReadTool/chimericReadSearch.py Line 728:

"results = processReads(samfile_path, exonTrees, repeatTrees, chimericBedFile)"

& 114

"repeat_results1 = repeatTrees[str(chr)].findRange([start1,end1])"

my resource file are in the same format than lions example and chromosome name is the same in the three files

**Comment by ababaian** [comment]
This may be an issue with pysam; can you post which version you are using.

**Comment by b12loroc** [comment]
pysam 0.13 version

2018-02-06 12:28 GMT+01:00 Carmen Maria Lopez Rodriguez <b12loroc@gmail.com>
:

**Comment by b12loroc** [comment]
Good afternoon Artem,
i run lions by a bam file, this file was aligned by STAR, i do not use
-tophat2, would this be a problem? how do you input a paired sample with
two fastq files in Lions? for example, input list with paired reads in two
files.
Or is necessary to use an interleaved file???
Cheers
Thank you
Sorry for any inconvenience caused!
Carmen María López Rodríguez

2018-02-06 13:35 GMT+01:00 Carmen Maria Lopez Rodriguez <b12loroc@gmail.com>
:

**Comment by b12loroc** [comment]
I have run Lions again. My input files this time were your samples (H1rep1,Gmrep...), paired reads in fastq format. Alignment with Tophat gave me the next error:
`[2018-02-07 13:20:31] Generating SAM header for hg38_illumina
Traceback (most recent call last):
  File "/mnt/backup/soft/tophat/programs/x86_64/2.0.13/tophat", line 4088, in <module>
    sys.exit(main())
  File "/mnt/backup/soft/tophat/programs/x86_64/2.0.13/tophat", line 3942, in main
    params.read_params = check_reads_format(params, reads_list)
  File "/mnt/backup/soft/tophat/programs/x86_64/2.0.13/tophat", line 1840, in check_reads_format
    freader=FastxReader(zf.file, params.read_params.color, zf.fname)
  File "/mnt/backup/soft/tophat/programs/x86_64/2.0.13/tophat", line 1585, in __init__
    while hlines>0 and self.lastline[0] not in "@>" :
IndexError: string index out of range`
Thanks
