### ISSUE TITLE
Post Calculate Exon/Repeat Interactions error: 0 regions loaded from file

### ISSUE THREAD

**Issue by synanth** [ababaian/LIONS#26]
Hi, 
I've been trying to run LIONS on some data and have run across the following issue:
RegionsCoverageFromWigCalculator fails to run as chromosomal analysis is skipped because they haven't been included in the region file. It looks like its failing at chimericReadSearch.py.

**Comment by synanth** [comment]
`$Id: RegionsCoverageFromWigCalculator.java 82545 2012-08-09 04:05:11Z mbilenky $
Loading chromosome lengths from /mnt/beegfs/home/stexocaelum/li_lab/me_cfs/LIONS/resources/hg38/genome/hg38.chr.size
Lengths for 455 chromosomes are loaded
load /mnt/beegfs/home/stexocaelum/li_lab/me_cfs/LIONS/projects/me_cfs/me_cfs/tmp_uniq_repeat_coords
0 regions loaded from file
Skipping analysis on chr 1 because this chr was not included in the region file

... (a whole bunch of the same)

Skipping analysis on chr KI270394.1 because this chr was not included in the region file
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.Comparable.compareTo(Object)" because "k1" is null
	at java.base/java.util.TreeMap.compare(TreeMap.java:1569)
	at java.base/java.util.TreeMap.addEntryToEmptyMap(TreeMap.java:776)
	at java.base/java.util.TreeMap.put(TreeMap.java:785)
	at java.base/java.util.TreeMap.put(TreeMap.java:534)
	at java.base/java.util.TreeSet.add(TreeSet.java:255)
	at src.tools.RegionsCoverageFromWigCalculator.execute(RegionsCoverageFromWigCalculator.java:255)
	at src.tools.RegionsCoverageFromWigCalculator.main(RegionsCoverageFromWigCalculator.java:55)`

**Comment by ababaian** [comment]
@synanth Sorry I keep meaning ot get to this but have been swamped the last couple of weeks! My apologies.

Can I recommend trying `ChimeraTE` (https://www.biorxiv.org/content/10.1101/2022.09.05.505575v1.full) which is written by actual software developers. This program has very similar core functionality to LIONS, but it's probably 200% more usable.
